index: 1
description: من می خواهم چیزهای پایه ای را که می توانم برای افزایش امنیت ایمیل خود
  انجام دهم را  بدانم. من باید بدانم که باید چه کار کنم اگر من فکر می کنم ایمیل من
  هک شده است.
title: مبتدی
